### PR TITLE
REORG: Modified conf.py and file location to build minimal example.

### PR DESCRIPTION
**Pull request by rossbar**
First off I just wanted to say that the progress you all are making is amazing! Thanks for all the hard work.

I was interested in trying out the new .md parser + sphinx pipeline and was planning on using one of the chapters from the [Elegant Scipy](https://github.com/elegant-scipy/elegant-scipy) to test some features for scientific publishing. As far as I can tell, you had similar intentions with this repo, so I decided to start here instead - again, thanks for putting this together.

It seems like things are moving very fast so I'm not sure I have the organization of everything straight, but it seems like the "new .md" parser is now mostly wrapped up in the [myst_parser](https://github.com/ExecutableBookProject/myst_parser) repo, so I modified the install instructions for the sphinx project in `doc/`.

The remainder of the changes are related to updating the `conf.py` and moving some files around to get the absolute minimum example (i.e. a sphinx page with content from `example.md` only) building. I am using this as a starting point for testing with the more full-featured example in `wealth_dynamics.md`. 

Please feel free to close this PR if this is too much of a distraction at this point with all of the rapid development happening. I will keep working in my fork and potentially make future PR's, but if you don't have the bandwidth to review them at the moment please let me know so I'm not spamming.

### CODE REVIEW

**Comment by choldgraf** [comment]
Hey! Thanks for chiming in :-) I am happy you think it's looking good!

Wanna add this as a PR to the `myst_parser` instead? We moved the sample pages from this repository to the docs in that repo so it's quicker to compare and iterate. I think the only thing to make sure is that the PRs adhere to the pre-commit checks (flake8 and black). WDYT?

**Comment by rossbar** [comment]
No problem! I will look at the docs folder in `myst_parser` and make sure the changes are still relevant. In the meantime I've been getting the more full-featured (i.e. with the `wealth_distributions.md` file) working so I will see if I can't move those changes over to `myst_parser/doc` as well.

**Comment by rossbar** [comment]
Turns out the changes I made here are no longer relevant :)

**Comment by choldgraf** [comment]
lol...well thanks for making them anyway :-)

**Pull request closed without merging**
